# ===================================================
# Cloud Run Service Configuration
# Deploy using: gcloud run services replace cloudrun.yaml
# ===================================================
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pharmaec-backend
  labels:
    cloud.googleapis.com/location: asia-south1
spec:
  template:
    metadata:
      annotations:
        # Minimum instances to prevent cold starts (costs money but faster)
        autoscaling.knative.dev/minScale: "1"
        # Maximum instances for scaling
        autoscaling.knative.dev/maxScale: "10"
        # CPU always allocated (prevents sleeping) - use for production
        run.googleapis.com/cpu-throttling: "false"
        # Startup CPU boost for faster cold starts
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/pharmaec-backend:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: latest
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: latest
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
