"""add_selling_price_final

Revision ID: 27c58952c609
Revises: 50c6e9355f48
Create Date: 2026-01-18 19:22:38.801243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c58952c609'
down_revision: Union[str, None] = '50c6e9355f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('employees', 'email',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.drop_column('roles', 'permissions')
    # op.alter_column('sessions', 'refresh_token',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=500),
    #            existing_nullable=False)
    op.add_column('shop_stock', sa.Column('selling_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_stock', 'selling_price')
    # op.alter_column('sessions', 'refresh_token',
    #            existing_type=sa.String(length=500),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)
    # op.add_column('roles', sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True))
    # op.alter_column('employees', 'email',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True)
    # ### end Alembic commands ###
