"""add_rack_fields_to_warehouse_stock

Revision ID: 6cbf7e558e1c
Revises: f5g6h7i8j9k0
Create Date: 2026-01-10 23:53:11.407946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cbf7e558e1c'
down_revision: Union[str, None] = 'f5g6h7i8j9k0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_shop', table_name='user_shop_access')
    op.drop_table('user_shop_access')
    op.drop_index('idx_user_warehouse', table_name='user_warehouse_access')
    op.drop_table('user_warehouse_access')
    op.drop_index('idx_rack_number', table_name='racks')
    op.drop_constraint('racks_rack_number_key', 'racks', type_='unique')
    op.create_index(op.f('ix_racks_rack_number'), 'racks', ['rack_number'], unique=True)
    op.add_column('warehouse_stock', sa.Column('rack_name', sa.String(length=100), nullable=True))
    op.add_column('warehouse_stock', sa.Column('rack_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse_stock', 'rack_number')
    op.drop_column('warehouse_stock', 'rack_name')
    op.drop_index(op.f('ix_racks_rack_number'), table_name='racks')
    op.create_unique_constraint('racks_rack_number_key', 'racks', ['rack_number'])
    op.create_index('idx_rack_number', 'racks', ['rack_number'], unique=False)
    op.create_table('user_warehouse_access',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_warehouse_access_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='user_warehouse_access_warehouse_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_warehouse_access_pkey')
    )
    op.create_index('idx_user_warehouse', 'user_warehouse_access', ['user_id', 'warehouse_id'], unique=True)
    op.create_table('user_shop_access',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['medical_shops.id'], name='user_shop_access_shop_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_shop_access_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_shop_access_pkey')
    )
    op.create_index('idx_user_shop', 'user_shop_access', ['user_id', 'shop_id'], unique=True)
    # ### end Alembic commands ###
